### ISSUE TITLE
Pricing rares

### ISSUE THREAD

**Issue by MLanghof** [thirdy/POE-TradeMacro#1]
Hey there,

I've long thought about a way to allow accurate automatic pricing of rares. When humans perform that process, they're clearly both looking at the rolls (and desirability) of the individual affixes, as well as the synergy between them. A key aspect is learning the "weightings" for all the affixes and synergistic aspects.

My idea would be to train a neural network on the rares available (or sold?) on the market, which takes as input the roll values of the affixes and outputs a numerical price (e.g. in chaos). This comes very close to the "human way", but would  I've delved a bit into the idea but got stopped short by the closure of Trackpete's API.

Key questions would be:

- What structure should the network have (and what library/learning to use)?
- How can "mispriced" rares be filtered out? Maybe only items that leave the market should be used for training (of which the overwhelming majority should be sold, so well-priced). In any case, guarding against abuse/manipulation would be necessary.
- Where does the training happen? Ideally a subscription to the API "river" of GGG would be used, to have information on item "movement" (as opposed to just listings on poe.trade) and also to keep training the network with as much data as possible, but how would users acquire the weightings (it wouldn't make sense to have every user train their own network)? I suppose ideally there would be a server that does this and responds to pricing requests of arbitrary rares, but that's a completely different dimension than this project is (apparently) going for. I suppose users could download (as in, have the program auto-download) a network weighting every now and then from the training server (would this raise security concerns in users?).
- How would item bases (and base types) be accounted for? Should the same net handle amulets and chests (which would probably emphasize the desirability of life rolls in general) or should they be different? What about 1h maces vs 2h maces vs daggers? Maybe it would be best to just feed base damage, attack speed, implicit value (and level/stat requirements) to the net instead of a number representing the progression in base items.

Let me know your thoughts!

**Comment by thirdy** [comment]
It's a cool project. But this requires infrastructure to be able to consume GGG's river API. For now, I am more interested in making tools that makes it easier to play PoE with only small effort. In other words, I'm a total noob on ML.

**Comment by Lachann** [comment]
Have you thought about incorporating something like this: http://poeprices.info/ for rares?

**Comment by thirdy** [comment]
That website is really nice, lot's work went into that.

Not sure yet how will I use that website as a service. But I'm concern with these:
```
(2) Availability. I don't have a dedicated host yet. I will try to keep it up 24/7 as much as I can. 

(3) Speed. Only one computer is supporting the browsing, searching and indexing. It will be slow when handling multiple requests, especially the batch searches. Please be patient and gentle.

(4) Index update. I do my own index, which I hope I can update once three days.
```
(taken from forum thread)

Speed is key. That demo from hegemony shows how really nice it is to use (except for us in the third world) TradeMacro on fast internet. Showing the top X items seems to be really great too.

**Comment by thirdy** [comment]
Will close this ticket as OP's suggestion is for a new project and is definitely out of scope of AHK.
Solution to price rares is not price rares (will create a new ticket for it and describe how will we solve it)
