### ISSUE TITLE
Item info for shaped maps shows incorrect level and "upgrades to"

### ISSUE THREAD

**Issue by xanthics** [thirdy/POE-TradeMacro#16]
See attached image, Shaped Jungle Valley (t6, level 73) upgrades to Arachnid Tomb.  However iteminfo states it is level 68 and upgrades to beach(the unshaped map).

![screenshot-0008](https://cloud.githubusercontent.com/assets/3137623/19203129/7a9b4672-8c8a-11e6-82bd-0b1c28b4c5fb.png)

**Comment by Eruyome** [comment]
That's a problem with Poe-ItemInfo, we don't touch that code, only use it. You should test and report it [here](https://github.com/aRTy42/POE-ItemInfo/issues)
