### ISSUE TITLE
Nothing happens when I press ctrl+i

### ISSUE THREAD

**Issue by sherifusa1988** [thirdy/POE-TradeMacro#20]
When I press ctrl+c I get a description for the items no problem, but when I press ctrl+i or ctrl+w, nothing happens whatsoever

**Comment by Eruyome** [comment]
Are you executing run.ahk to start the script?

**Comment by sherifusa1988** [comment]
I am sorry could u be more specific? I double click the macro and it runs in my tray, I have AutoHotkey

**Comment by Eruyome** [comment]
There is a file "run.ahk" in the root directory, if you run any other .ahk file instead of this one you're doing it wrong and it won't work. A lot of people having the same problem as you're describing made that mistake.

**Comment by thirdy** [comment]
I think we should just rename `run.ahk` to `Run.ahk`.

And `POE-ItemInfo.ahk` into something else like `pii.data`, so it's not runnable (we do this only in the release zip)

**Comment by Eruyome** [comment]
Yeah, maybe... we could also just name it "PLEASE_RUN_ONLY_THIS_FILE_HERE.ahk". 

Back to the problem at hand, most probably it is because of starting the wrong file.
