### ISSUE TITLE
GUI for TradeMacro has 2xDefault, OK, Cancel

### ISSUE THREAD

**Issue by TheOne320** [thirdy/POE-TradeMacro#21]
As the title says, the GUI currently had double the needed default, ok, cancel buttons.

**Comment by Eruyome** [comment]
Are you talking about the version on the development branch? If yes that's intended. Long story shot, wihtout changing POE-ItemInfos code we need to implement our own buttons to handle the operations triggered by them. And we don't change theri code, just pull their updates.
