### ISSUE TITLE
Advanced search result tooltip sometimes broken

### ISSUE THREAD

**Issue by Eruyome** [thirdy/POE-TradeMacro#24]
Formatting is sometimes broken.

**Comment by thirdy** [comment]
will need to check if even a simple hello world gui causes this issue.

also i don't think we implemented the this cleanly

**Comment by Eruyome** [comment]
You mean the Gui or the Tooltip?

**Comment by thirdy** [comment]
http://stackoverflow.com/questions/25722818/autohotkey-inputbox-with-multiline-input

using blocking input dialog might solve this. from testing it multiple times, it seems to be a problem with how we use the callback

**Comment by Eruyome** [comment]
After using the advanced search (ctrl+alt+d), function AdvancedPriceSearchGui(), the tooltip uses the default font again.
