### ISSUE TITLE
"Lair Map" is pulling price data for "Spider Lair Map"

### ISSUE THREAD

**Issue by xanthics** [thirdy/POE-TradeMacro#3]
Presumably this would also happen with "Shrine Map" and "Overgrown Shrine Map"

**Comment by xanthics** [comment]
This also happens with "Ivory Temple Map" and "Temple Map"

"Ivory Temple Map" also has the ctrl+c information for "Temple Map"

**Comment by Eruyome** [comment]
So far the search doesn't use item type and base, should be implemented in the future. Searching by name only gives the same results on poe.trade.

**Comment by Eruyome** [comment]
Fixed/implemented
