### ISSUE TITLE
Can't run the script

### ISSUE THREAD

**Issue by JCDenis1** [thirdy/POE-TradeMacro#31]
Got this message when i tried to start run.ahk - http://pix.my/O7rVSTh6.
Can you, please, help how to fix it?

**Comment by Eruyome** [comment]
Please update your autohotkey installation to the latest version, that should fix it. Let me know if it doesn't.

**Comment by Eruyome** [comment]
Please update your autohotkey installation to the latest version, that should fix it. Let me know if it doesn't.

**Comment by JCDenis1** [comment]
Update helped, thanks.
