### ISSUE TITLE
Ctrl + Q

### ISSUE THREAD

**Issue by nicksloan11** [thirdy/POE-TradeMacro#32]
Was this removed? It's not working for the release or dev build.

**Comment by Eruyome** [comment]
Since I answered this way to often now, have you read the instructions in the readme and followed them? If not, please do so and it will probably fix your problems.

**Comment by Eruyome** [comment]
I can check that later, have been working on the development branch for so long now that I'm not sure about what worked in the previous version, but it definitely wasn't removed.
