### ISSUE TITLE
Get FunctionGetLatestRelease() to work correctly

### ISSUE THREAD

**Issue by Eruyome** [thirdy/POE-TradeMacro#5]
`tag := StrX( html,  "<span class=""tag-name",N,0,  "</span>", 1,0, N )`
returns `2.4.01` instead of `1.0` on [releases](https://github.com/thirdy/POE-TradeMacro/tags)

**Comment by thirdy** [comment]
I think this would do:

https://api.github.com/repos/thirdy/POE-TradeMacro/releases/latest

I think it gives the latest release (and not pre-relase)

**Comment by Eruyome** [comment]
Didn't knew that url, seems right for the job.
