### ISSUE TITLE
Shortcuts not working (ctrl+x/w/i)

### ISSUE THREAD

**Issue by Diegoslp** [thirdy/POE-TradeMacro#7]
ctrl x  stopped working for me, since last update: **db586fd**

**Comment by Eruyome** [comment]
Everything works fine for me.

You're using the latest version instead of the latest release version.  Some questions:
1. What version is the last that worked for you?
2. Did you follow the dev version instructions in the readme?
3. Do the other shortcuts still work (ctrl+c, ctrl+w, ctrl+i)?
4. How did you update from your last version? Fresh reinstall would be the best.

**Comment by Eruyome** [comment]
Running the script as admin should fix this problem.

**Comment by Diegoslp** [comment]
1. all my stuff are fully upgraded
2. yes
3. only ctrl+c still working
4. I always do the complete fresh reinstall

**Comment by Eruyome** [comment]
Can you tell me what operating system you have?

**Comment by Diegoslp** [comment]
Windows 10 Pro x64 fully upgraded

**Comment by Eruyome** [comment]
Do you use for example a russian keyboard layout, or simple one that is differten from the typical english/us/german? If that's the case try switching to english.

**Comment by Diegoslp** [comment]
i'm using a brazilian keyboard, i changed the keyboard to EN-US and my crtl+x still broken. before you release the update: db586fd everything was working normally and i did not have to change anything on my keyboard that was set to PT-BR as usual.

**Comment by Eruyome** [comment]
I find that very confusing, nothing in that commit should break anything hotkey related. Can you make sure it's really the one you mentioned (if you haven't already done that)?
The commit you mentioned: [db586fd](https://github.com/thirdy/POE-TradeMacro/archive/db586fd47a462cc043b7737aae6e078b3ecdced9.zip)
The one before it: [18f3d29](https://github.com/thirdy/POE-TradeMacro/archive/18f3d29a44978a53ad444cad2371b353f7abdb49.zip)
THe one after it: [0a25942](https://github.com/thirdy/POE-TradeMacro/archive/0a259425986a99c5c5ec669b2cbc2f7a9813d4e2.zip)

**Comment by Diegoslp** [comment]
i just Run the _run.ahk_ rather than _POE-ItemInfo.ahk_ and its work well, all hotkeys works.

**Comment by Eruyome** [comment]
Well, that's what you are supposed to do. Glad everything works.

**Comment by kyri0** [comment]
Yeah, if you only run iteminfo, then only the iteminfo hot keys will work.

**Comment by thirdy** [comment]
Hey guys, I got this job interview, so I'm missing in action for a week or two. Cheers!

**Comment by TheOne320** [comment]
Break a leg!
